import Product from "../src/application/domain/Product";

// export const products = [
//     new Product(0, `http://localhost:${Math.random()}/`, "", "1", ""),
//     new Product(0, `http://localhost:${Math.random()}/`, "", "2", ""),
//     new Product(0, `http://localhost:${Math.random()}/`, "", "3", ""),
//     new Product(0, `http://localhost:${Math.random()}/`, "", "4", ""),
//     new Product(0, `http://localhost:${Math.random()}/`, "", "5", ""),
//     new Product(0, `http://localhost:${Math.random()}/`, "", "6", ""),
// ]


export const products: Product[] = [
    new Product(49.99, "https://example.com/images/product0.jpg", "Nike", "1", "Sneaker"),
    new Product(29.99, "https://example.com/images/product1.jpg", "Adidas", "2", "T-Shirt"),
    new Product(89.99, "https://example.com/images/product2.jpg", "Puma", "3", "Jacket"),
    new Product(19.99, "https://example.com/images/product3.jpg", "Reebok", "4", "Shorts"),
    new Product(14.99, "https://example.com/images/product4.jpg", "Under Armour", "5", "Hat"),
    new Product(59.99, "https://example.com/images/product5.jpg", "Nike", "6", "Sneaker"),
    new Product(35.99, "https://example.com/images/product6.jpg", "Adidas", "7", "T-Shirt"),
    new Product(95.99, "https://example.com/images/product7.jpg", "Puma", "8", "Jacket"),
    new Product(22.99, "https://example.com/images/product8.jpg", "Reebok", "9", "Shorts"),
    new Product(17.99, "https://example.com/images/product9.jpg", "Under Armour", "10", "Hat"),
    new Product(49.49, "https://example.com/images/product10.jpg", "Nike", "11", "Sneaker"),
    new Product(28.49, "https://example.com/images/product11.jpg", "Adidas", "12", "T-Shirt"),
    new Product(88.79, "https://example.com/images/product12.jpg", "Puma", "13", "Jacket"),
    new Product(19.49, "https://example.com/images/product13.jpg", "Reebok", "14", "Shorts"),
    new Product(15.49, "https://example.com/images/product14.jpg", "Under Armour", "15", "Hat"),
    new Product(62.99, "https://example.com/images/product15.jpg", "Nike", "16", "Sneaker"),
    new Product(31.99, "https://example.com/images/product16.jpg", "Adidas", "17", "T-Shirt"),
    new Product(92.49, "https://example.com/images/product17.jpg", "Puma", "18", "Jacket"),
    new Product(24.49, "https://example.com/images/product18.jpg", "Reebok", "19", "Shorts"),
    new Product(16.99, "https://example.com/images/product19.jpg", "Under Armour", "20", "Hat"),
    new Product(53.99, "https://example.com/images/product20.jpg", "Nike", "21", "Sneaker"),
    new Product(33.49, "https://example.com/images/product21.jpg", "Adidas", "22", "T-Shirt"),
    new Product(87.99, "https://example.com/images/product22.jpg", "Puma", "23", "Jacket"),
    new Product(21.99, "https://example.com/images/product23.jpg", "Reebok", "24", "Shorts"),
    new Product(18.49, "https://example.com/images/product24.jpg", "Under Armour", "25", "Hat"),
    new Product(60.49, "https://example.com/images/product25.jpg", "Nike", "26", "Sneaker"),
    new Product(34.99, "https://example.com/images/product26.jpg", "Adidas", "27", "T-Shirt"),
    new Product(91.49, "https://example.com/images/product27.jpg", "Puma", "28", "Jacket"),
    new Product(23.99, "https://example.com/images/product28.jpg", "Reebok", "29", "Shorts"),
    new Product(17.29, "https://example.com/images/product29.jpg", "Under Armour", "30", "Hat"),
    new Product(56.99, "https://example.com/images/product30.jpg", "Nike", "31", "Sneaker"),
    new Product(32.49, "https://example.com/images/product31.jpg", "Adidas", "32", "T-Shirt"),
    new Product(85.99, "https://example.com/images/product32.jpg", "Puma", "33", "Jacket"),
    new Product(20.99, "https://example.com/images/product33.jpg", "Reebok", "34", "Shorts"),
    new Product(19.49, "https://example.com/images/product34.jpg", "Under Armour", "35", "Hat"),
    new Product(54.99, "https://example.com/images/product35.jpg", "Nike", "36", "Sneaker"),
    new Product(30.49, "https://example.com/images/product36.jpg", "Adidas", "37", "T-Shirt"),
    new Product(90.99, "https://example.com/images/product37.jpg", "Puma", "38", "Jacket"),
    new Product(25.99, "https://example.com/images/product38.jpg", "Reebok", "39", "Shorts"),
    new Product(15.29, "https://example.com/images/product39.jpg", "Under Armour", "40", "Hat"),
    new Product(62.49, "https://example.com/images/product40.jpg", "Nike", "41", "Sneaker"),
    new Product(33.99, "https://example.com/images/product41.jpg", "Adidas", "42", "T-Shirt"),
    new Product(84.99, "https://example.com/images/product42.jpg", "Puma", "43", "Jacket"),
    new Product(22.49, "https://example.com/images/product43.jpg", "Reebok", "44", "Shorts"),
    new Product(18.99, "https://example.com/images/product44.jpg", "Under Armour", "45", "Hat"),
    new Product(57.99, "https://example.com/images/product45.jpg", "Nike", "46", "Sneaker"),
    new Product(31.49, "https://example.com/images/product46.jpg", "Adidas", "47", "T-Shirt"),
    new Product(87.49, "https://example.com/images/product47.jpg", "Puma", "48", "Jacket"),
    new Product(20.29, "https://example.com/images/product48.jpg", "Reebok", "49", "Shorts"),
    new Product(17.79, "https://example.com/images/product49.jpg", "Under Armour", "50", "Hat"),
    new Product(64.99, "https://example.com/images/product50.jpg", "Nike", "51", "Sneaker"),
    new Product(29.79, "https://example.com/images/product51.jpg", "Adidas", "52", "T-Shirt"),
    new Product(89.49, "https://example.com/images/product52.jpg", "Puma", "53", "Jacket"),
    new Product(23.29, "https://example.com/images/product53.jpg", "Reebok", "54", "Shorts"),
    new Product(16.49, "https://example.com/images/product54.jpg", "Under Armour", "55", "Hat"),
    new Product(55.49, "https://example.com/images/product55.jpg", "Nike", "56", "Sneaker"),
    new Product(34.99, "https://example.com/images/product56.jpg", "Adidas", "57", "T-Shirt"),
    new Product(85.29, "https://example.com/images/product57.jpg", "Puma", "58", "Jacket"),
    new Product(24.99, "https://example.com/images/product58.jpg", "Reebok", "59", "Shorts"),
    new Product(17.99, "https://example.com/images/product59.jpg", "Under Armour", "60", "Hat"),
    new Product(61.49, "https://example.com/images/product60.jpg", "Nike", "61", "Sneaker"),
    new Product(33.49, "https://example.com/images/product61.jpg", "Adidas", "62", "T-Shirt"),
    new Product(92.49, "https://example.com/images/product62.jpg", "Puma", "63", "Jacket"),
    new Product(22.29, "https://example.com/images/product63.jpg", "Reebok", "64", "Shorts"),
    new Product(18.79, "https://example.com/images/product64.jpg", "Under Armour", "65", "Hat"),
    new Product(58.99, "https://example.com/images/product65.jpg", "Nike", "66", "Sneaker"),
    new Product(32.29, "https://example.com/images/product66.jpg", "Adidas", "67", "T-Shirt"),
    new Product(86.49, "https://example.com/images/product67.jpg", "Puma", "68", "Jacket"),
    new Product(23.49, "https://example.com/images/product68.jpg", "Reebok", "69", "Shorts")]